### PR TITLE
feat: Add support for `og` image generation

### LINKED ISSUE #2: Support for `og` image generation on the website
# Feature request

Right now, our website doesn't have any `og` image for pages and something that looks cool should work 🎨

For more context, check this out: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation

### PR DESCRIPTION
**Pull request by dephraiim**
## Feature
feature: Add support for `og` image generation

## Related Issue
Closes #2 

## Screenshot
og

### CODE REVIEW

**Comment by yeganathan18** [comment]
Wow! how did you setup the local development without the env file.

**Comment by yeganathan18** [comment]
I think design can be improved a bit, let me share the modified version of the same.

**Comment by dephraiim** [comment]
> Wow! how did you setup the local development without the env file.

Supabase is needed and I figured I don't need supabase for the og so I commented the file out to avoid any errors and removed the comment before I pushed it.

This is it..
https://github.com/gitwonk/gitwonk/blob/bec14be67d7879f00bf275dd44c2136748561a5a/apps/www/lib/supabase.ts#L3-L6

**Comment by yeganathan18** [comment]
@dephraiim good thinking, but no worries, I just updated the env file with values and also documented the same in [`DEVERLOPERS.md`](https://github.com/gitwonk/gitwonk/blob/main/DEVELOPERS.md#running-turborepo) Let me know if there are still any issues with the local setup!

(It might help future contributors set up the project locally without any hassle)

**Comment by yeganathan18** [comment]
Can you update the PR with just your commits and code? It looks like the PR is not rebased properly 🤔

**Comment by dephraiim** [comment]
I think I merged the first commit into your commit. I don't think that should be a problem. 

If it becomes a problem , the best option will be to close the PR and reopen another without those changes

**Comment by yeganathan18** [comment]
That's actually not a good practice of merging PRs and you either hard or soft reset, pull the `main` branch once again should fix the issue.

**Pull request closed without merging**
